# Mersey I - Introduction {#SecondPractical}

Within a Geographical Information System (GIS) framework, readily available spatial datasets, such as land use and geology, have been used to explore the controls on river water quality. Understanding the relationships between catchment characteristics (or metrics) and river water quality provides a base for determining how future changes in both land use and climate will impact river water quality. Therefore, it is important to determine the processes that regulate river water quality in landscapes under increasing pressure from human population, whether from urbanisation or more intensive food production.

The **Mersey Basin** is one of the UK’s most environmentally varied regions, with rich rural landscapes and urban-industrial centres. Industrial prosperity in the region over the last few hundred years resulted in severe pollution of the many rivers in the basin. Although there has been significant improvements in water quality in recent years the rivers in the Mersey Basin are still subjected to a number of sewage and industrial inputs, and agricultural runoff.

You can explore the basin below:

```{r, echo = FALSE, fig.align="center", warning = FALSE, message = FALSE}

# Loads library and shapefile
library(rgdal)
mersey_watershed <- readOGR(here("data", "practical_2", "mersey_watershed_basin.shp"), 
                            layer = "mersey_watershed_basin", verbose = FALSE)

# Transform to WGS 84
mersey_watershed <- spTransform(mersey_watershed, CRS("+proj=longlat +datum=WGS84"))

m <- leaflet() %>%
  # Sets view
  setView(lat=53.47722932957252, lng = -2.243114768566372, zoom = 9) %>%
  # Adds default tiles
  addTiles()  %>%
  # Add polygon
  addPolygons(data=mersey_watershed, color = "#444444", fillColor = "#33b9ff", 
              weight = 1, smoothFactor = 0.5, opacity = 0.9, fillOpacity = 0.3) %>%
  # Adds marker for the catchment outlet
  addMarkers(lat=53.3565240, lng = -2.6704572, popup = "Mersey Basin outlet")

m
```

## Overview

In this practical you will explore the controls on river water quality in the Mersey
Basin and develop empirical models of river water quality across the region.

### Topics covered in this practical

- Terrain analysis, including catchment delineation and derivation of catchment characteristics;
- Writing and execution of scripts;
- Multiple Linear Regression to create models of catchment hydrochemistry;
- Using models to create spatial predictions of catchment hydrochemistry using [WhiteboxTools](https://jblindsay.github.io/wbt_book/intro.html).

### Intended Learning Outcomes

- Gain practical experience of modelling environmental phenomena using a Geographical Information Systems (GIS) framework;
- Gain practical experience of hydrological modelling using GIS;
- Gain practical experience of manipulating and analysing raster datasets;
- Gain practical experience of using Map Algebra functions and writing scripts;
- Gain practical experience of using multivariate analysis;
- Understand some of the key controls on river water quality;
- Be able to critically evaluate model outputs.

### Assessment

This practical is assessed by completion of the tasks outlined in this document, full details of which are provided [here](#Assessment). You will need to write up the practical in the format of a report. This practical is worth 50% of your overall mark for GEOG70581. 

As well as the standard SEED PGT criteria, you will also be assessed on your ability to:

- Effectively follow instructions to complete the practical tasks (technical prowess), i.e. producing the regression equations and output images correctly; 
- Analyse and interpret the outputs in the context of your knowledge of river hydrochemistry (and with reference to appropriate literature); 
- Relate the monitoring and modelling approaches here to theory covered earlier in the course (and with reference to appropriate literature);
- Explain ideas clearly and concisely; 
- Present figures and data clearly and effectively; 
- Be original and insightful in terms of independent research and additional analysis of the data where appropriate.
- Use references to relevant academic literature to support your arguments;


<div align="center">The **deadline** for this practical is 2pm on Thursday 4th February 2021.

The **word count** for this practical is 2,000.</div>
