---
output:
  word_document: default
  html_document: default
  pdf_document: default
---
# Assessment {#Assessment}

**Title:** Modelling River Hydrochemistry in the Mersey Basin, UK

**Primary aims**

In addition to the specific points outlined below, your report should:

- **Explore** the controls on river water quality in the Mersey Basin.
- **Develop** empirical models which link river water quality (e.g. pH, Mg, Ca...) to catchment characteristics (e.g. land cover, topography, soils, bedrock).
- **Explain** the trends shown in these models, with reference to relevant hydrological literature and hydrological-environmental processes.
- **Assess** the quality of the models, with reference to key concepts covered in the course so far. 

**Word Limit:** 1,500. The guidelines provided in the CO<sub>2</sub> flux practical, which outline what is and what is not included in the word count, as well penalties for exceeding the word count, also apply here. 

**Intended Learning Outcomes**: see [Mersey I - Introduction](#SecondPractical)

**Assessment Criteria**: see the [Assessment Guidance](https://online.manchester.ac.uk/ultra/courses/_83595_1/cl/outline) section on Blackboard, which includes a marking rubric and hints-and-tips presentation, as well as [Mersey I - Introduction](#SecondPractical)

**Format:** Report 

**Structure:** Your report should be a coherent document, as opposed to a list of Q&As as with the CO<sub>2</sub> flux practical. Within this, how you structure the report is your decision. However, there are certain items that must be included in the main body of the report. These are the regression equations (and associated information i.e. significance values, R<sup>2</sup> etc) for all ten water quality indicators. 

This could be presented as a table, perhaps in the format shown below:

|    Indicator   |                                      Equation                                     | R<sup>2</sup> | *p* value | Additional columns as required |
|:--------------:|:---------------------------------------------------------------------------------:|:-------------:|:---------:|:------------------------------:|
| Zn | $Zn = 11.31 + (0.43 \cdot Urban \: percent)$ | 0.36          | < 0.01    |                                |
|                |                                                                                   |               |           |                                |
|                |                                                                                   |               |           |                                |

As well as these important items, the following points should be covered in the report: 

1. What are the relationships between water quality and catchment characteristics? 

2. Are there any consistent predictors of water quality? 

3. How good are the regression models? 

4. What sort of errors may occur during the derivation of catchment characteristics? 

5. How could these errors be minimised?

6. How could you validate the models? 

7. Your regression models could be used to predict water quality in different catchments or different sub-basins of the Mersey. Can you think of any possible errors / limitations when making predictions of this type? 

Your report should not just be a reworked version of the practical instructions. **Do not** include a ‘methodology’ section at all, although you may wish to reflect on the methods used when considering the points above. You may find it useful to refer to the my learning essential resources on [report writing](https://www.library.manchester.ac.uk/using-the-library/students/training-and-skills-support/my-learning-essentials/online-resources/). 

In addition to the above, we would like you to produce three output maps to visualise the practical steps. These should be included in an Appendix at the back of the report (ideally two images per page). These should include the layers listed below but can include others to improve map design (e.g. an elevation background). 

- a map showing the flow accumulation network (`mersey_dem_flow_accumulation.tif`), using log-transformed values and specific contributing areas;
- a map showing the watersheds in the Mersey Basin (`mersey_watersheds.shp`), derived from the 70 modified Environment Agency seed points;
- a map showing the reclassified soils raster (`mersey_HOST_reclass.tif`).

**Map design**: Normally, all maps should have a scale bar and north arrow. However, because we're using projected data (British National Grid) and because `ggpsatial` automatically adds informative latitude/longitude axes to your plots, you **don't** need to include either of these elements here. For reference, these can be added using `annotation_scale()` and `annotation_north_arrow()` respectively. Maps should, however, include informative legends, titles and axis labels, and should use colour-blind friendly and perceptually-uniform palettes. 

**Referencing**: The report should be fully referenced, using the Harvard style. You should not just adapt the text from the Rothwell et al. ([2010](https://doi.org/10.1016/j.jhydrol.2010.10.015)) paper, substituting key values for the data here. This will result in a high similarity index and you may face a penalty due to poor academic practice. You must write up the report in your own words, making sure you paraphrase the ideas of others, and reference fully throughout. 

**Submission deadline**: 09/01/2025, 14:00


