<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 11 Mersey V - Statistical analysis |  Hydrological analysis in R </title>
  <meta name="description" content="<br />
Hydrological analysis in R<br />
</center>" />
  <meta name="generator" content="bookdown 0.36 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 11 Mersey V - Statistical analysis |  Hydrological analysis in R " />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 11 Mersey V - Statistical analysis |  Hydrological analysis in R " />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="mersey_four.html"/>
<link rel="next" href="Assessment.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.3/htmlwidgets.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.2.1/leaflet.js"></script>
<script src="libs/leaflet-providers-2.0.0/leaflet-providers_2.0.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.2.1/leaflet-providers-plugin.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#practical-outline"><i class="fa fa-check"></i><b>1.1</b> Practical outline</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#objectives"><i class="fa fa-check"></i><b>1.2</b> Objectives</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#schedule"><i class="fa fa-check"></i><b>1.3</b> Schedule</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="Installation.html"><a href="Installation.html"><i class="fa fa-check"></i><b>2</b> Installation</a>
<ul>
<li class="chapter" data-level="2.1" data-path="Installation.html"><a href="Installation.html#r"><i class="fa fa-check"></i><b>2.1</b> R</a></li>
<li class="chapter" data-level="2.2" data-path="Installation.html"><a href="Installation.html#r-studio"><i class="fa fa-check"></i><b>2.2</b> R Studio</a></li>
<li class="chapter" data-level="2.3" data-path="Installation.html"><a href="Installation.html#materials"><i class="fa fa-check"></i><b>2.3</b> Course materials</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="Intro_to_R.html"><a href="Intro_to_R.html"><i class="fa fa-check"></i><b>3</b> A (brief) introduction to R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="Intro_to_R.html"><a href="Intro_to_R.html#overview"><i class="fa fa-check"></i><b>3.1</b> Overview</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="Intro_to_R.html"><a href="Intro_to_R.html#what-is-r"><i class="fa fa-check"></i><b>3.1.1</b> What is R?</a></li>
<li class="chapter" data-level="3.1.2" data-path="Intro_to_R.html"><a href="Intro_to_R.html#why_code"><i class="fa fa-check"></i><b>3.1.2</b> Why code?</a></li>
<li class="chapter" data-level="3.1.3" data-path="Intro_to_R.html"><a href="Intro_to_R.html#a-quick-note-on-the-practicals"><i class="fa fa-check"></i><b>3.1.3</b> A quick note on the practicals</a></li>
<li class="chapter" data-level="3.1.4" data-path="Intro_to_R.html"><a href="Intro_to_R.html#dealing-with-errors"><i class="fa fa-check"></i><b>3.1.4</b> Dealing with errors</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="Intro_to_R.html"><a href="Intro_to_R.html#loading-r"><i class="fa fa-check"></i><b>3.2</b> Loading R</a></li>
<li class="chapter" data-level="3.3" data-path="Intro_to_R.html"><a href="Intro_to_R.html#variables-looping"><i class="fa fa-check"></i><b>3.3</b> Objects</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="Intro_to_R.html"><a href="Intro_to_R.html#object-names"><i class="fa fa-check"></i><b>3.3.1</b> Object names</a></li>
<li class="chapter" data-level="3.3.2" data-path="Intro_to_R.html"><a href="Intro_to_R.html#variables_types"><i class="fa fa-check"></i><b>3.3.2</b> Object types</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="Intro_to_R.html"><a href="Intro_to_R.html#data-structures"><i class="fa fa-check"></i><b>3.4</b> Data structures</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="Intro_to_R.html"><a href="Intro_to_R.html#vectors"><i class="fa fa-check"></i><b>3.4.1</b> Vectors</a></li>
<li class="chapter" data-level="3.4.2" data-path="Intro_to_R.html"><a href="Intro_to_R.html#data_frames"><i class="fa fa-check"></i><b>3.4.2</b> Data frames</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="Intro_to_R.html"><a href="Intro_to_R.html#scripts"><i class="fa fa-check"></i><b>3.5</b> Scripts</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="Intro_to_R.html"><a href="Intro_to_R.html#comments"><i class="fa fa-check"></i><b>3.5.1</b> Comments</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="Intro_to_R.html"><a href="Intro_to_R.html#packages"><i class="fa fa-check"></i><b>3.6</b> Loading packages</a></li>
<li class="chapter" data-level="3.7" data-path="Intro_to_R.html"><a href="Intro_to_R.html#data_loading"><i class="fa fa-check"></i><b>3.7</b> Loading data</a></li>
<li class="chapter" data-level="3.8" data-path="Intro_to_R.html"><a href="Intro_to_R.html#data_plotting"><i class="fa fa-check"></i><b>3.8</b> Plotting</a></li>
<li class="chapter" data-level="3.9" data-path="Intro_to_R.html"><a href="Intro_to_R.html#formative_task"><i class="fa fa-check"></i><b>3.9</b> Formative task</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="Intro_to_R.html"><a href="Intro_to_R.html#formative_solution_one"><i class="fa fa-check"></i><b>3.9.1</b> Formative solution</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="FirstPractical.html"><a href="FirstPractical.html"><i class="fa fa-check"></i><b>4</b> Eskdale I - Introduction</a>
<ul>
<li class="chapter" data-level="4.1" data-path="FirstPractical.html"><a href="FirstPractical.html#overview-1"><i class="fa fa-check"></i><b>4.1</b> Overview</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="FirstPractical.html"><a href="FirstPractical.html#intended-learning-outcomes"><i class="fa fa-check"></i><b>4.1.1</b> Intended learning outcomes</a></li>
<li class="chapter" data-level="4.1.2" data-path="FirstPractical.html"><a href="FirstPractical.html#assessment"><i class="fa fa-check"></i><b>4.1.2</b> Assessment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="Eskdale_set_up.html"><a href="Eskdale_set_up.html"><i class="fa fa-check"></i><b>5</b> Eskdale II - Set-up</a>
<ul>
<li class="chapter" data-level="5.1" data-path="Eskdale_set_up.html"><a href="Eskdale_set_up.html#install-programs"><i class="fa fa-check"></i><b>5.1</b> Install programs</a></li>
<li class="chapter" data-level="5.2" data-path="Eskdale_set_up.html"><a href="Eskdale_set_up.html#download_data"><i class="fa fa-check"></i><b>5.2</b> Download data</a></li>
<li class="chapter" data-level="5.3" data-path="Eskdale_set_up.html"><a href="Eskdale_set_up.html#open-rstudio"><i class="fa fa-check"></i><b>5.3</b> Open RStudio</a></li>
<li class="chapter" data-level="5.4" data-path="Eskdale_set_up.html"><a href="Eskdale_set_up.html#R_Projects"><i class="fa fa-check"></i><b>5.4</b> Initialise an R project</a></li>
<li class="chapter" data-level="5.5" data-path="Eskdale_set_up.html"><a href="Eskdale_set_up.html#creating-an-r-script"><i class="fa fa-check"></i><b>5.5</b> Creating an R script</a></li>
<li class="chapter" data-level="5.6" data-path="Eskdale_set_up.html"><a href="Eskdale_set_up.html#install-whiteboxtools"><i class="fa fa-check"></i><b>5.6</b> Install WhiteboxTools</a></li>
<li class="chapter" data-level="5.7" data-path="Eskdale_set_up.html"><a href="Eskdale_set_up.html#loading-packages"><i class="fa fa-check"></i><b>5.7</b> Loading packages</a></li>
<li class="chapter" data-level="5.8" data-path="Eskdale_set_up.html"><a href="Eskdale_set_up.html#errors-using-r-projects"><i class="fa fa-check"></i><b>5.8</b> Errors using R projects</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="Eskdale_flow_algorithms.html"><a href="Eskdale_flow_algorithms.html"><i class="fa fa-check"></i><b>6</b> Eskdale III - Flow routing</a>
<ul>
<li class="chapter" data-level="6.1" data-path="Eskdale_flow_algorithms.html"><a href="Eskdale_flow_algorithms.html#dem-pre-processing-flow-enforcement"><i class="fa fa-check"></i><b>6.1</b> DEM pre-processing: flow enforcement</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="Eskdale_flow_algorithms.html"><a href="Eskdale_flow_algorithms.html#data-description"><i class="fa fa-check"></i><b>6.1.1</b> Data description</a></li>
<li class="chapter" data-level="6.1.2" data-path="Eskdale_flow_algorithms.html"><a href="Eskdale_flow_algorithms.html#breaching-and-filling"><i class="fa fa-check"></i><b>6.1.2</b> Breaching and filling</a></li>
<li class="chapter" data-level="6.1.3" data-path="Eskdale_flow_algorithms.html"><a href="Eskdale_flow_algorithms.html#choosing-a-colour-ramp"><i class="fa fa-check"></i><b>6.1.3</b> Choosing a colour ramp</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="Eskdale_flow_algorithms.html"><a href="Eskdale_flow_algorithms.html#flow-parameters-pointers"><i class="fa fa-check"></i><b>6.2</b> Flow Parameters: Pointers</a></li>
<li class="chapter" data-level="6.3" data-path="Eskdale_flow_algorithms.html"><a href="Eskdale_flow_algorithms.html#flow-algorithms"><i class="fa fa-check"></i><b>6.3</b> Flow Algorithms</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="Eskdale_flow_algorithms.html"><a href="Eskdale_flow_algorithms.html#comparing-flow-algorithms"><i class="fa fa-check"></i><b>6.3.1</b> Comparing flow algorithms</a></li>
<li class="chapter" data-level="6.3.2" data-path="Eskdale_flow_algorithms.html"><a href="Eskdale_flow_algorithms.html#fd8-catchment-area"><i class="fa fa-check"></i><b>6.3.2</b> FD8 catchment area</a></li>
<li class="chapter" data-level="6.3.3" data-path="Eskdale_flow_algorithms.html"><a href="Eskdale_flow_algorithms.html#d-infinity-catchment-area"><i class="fa fa-check"></i><b>6.3.3</b> D-infinity catchment area</a></li>
<li class="chapter" data-level="6.3.4" data-path="Eskdale_flow_algorithms.html"><a href="Eskdale_flow_algorithms.html#comparing-the-outputs"><i class="fa fa-check"></i><b>6.3.4</b> Comparing the outputs</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="Eskdale_flow_algorithms.html"><a href="Eskdale_flow_algorithms.html#practical-solution"><i class="fa fa-check"></i><b>6.4</b> Practical solution</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="SecondPractical.html"><a href="SecondPractical.html"><i class="fa fa-check"></i><b>7</b> Mersey I - Introduction</a>
<ul>
<li class="chapter" data-level="7.1" data-path="SecondPractical.html"><a href="SecondPractical.html#overview-2"><i class="fa fa-check"></i><b>7.1</b> Overview</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="SecondPractical.html"><a href="SecondPractical.html#topics-covered-in-this-practical"><i class="fa fa-check"></i><b>7.1.1</b> Topics covered in this practical</a></li>
<li class="chapter" data-level="7.1.2" data-path="SecondPractical.html"><a href="SecondPractical.html#intended-learning-outcomes-1"><i class="fa fa-check"></i><b>7.1.2</b> Intended Learning Outcomes</a></li>
<li class="chapter" data-level="7.1.3" data-path="SecondPractical.html"><a href="SecondPractical.html#assessment-1"><i class="fa fa-check"></i><b>7.1.3</b> Assessment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="Mersy_set_up.html"><a href="Mersy_set_up.html"><i class="fa fa-check"></i><b>8</b> Mersey II - Set-up</a>
<ul>
<li class="chapter" data-level="8.1" data-path="Mersy_set_up.html"><a href="Mersy_set_up.html#practical-overview"><i class="fa fa-check"></i><b>8.1</b> Practical overview</a></li>
<li class="chapter" data-level="8.2" data-path="Mersy_set_up.html"><a href="Mersy_set_up.html#install-programs-1"><i class="fa fa-check"></i><b>8.2</b> Install programs</a></li>
<li class="chapter" data-level="8.3" data-path="Mersy_set_up.html"><a href="Mersy_set_up.html#download_data_v2"><i class="fa fa-check"></i><b>8.3</b> Download data</a></li>
<li class="chapter" data-level="8.4" data-path="Mersy_set_up.html"><a href="Mersy_set_up.html#practical-2-data"><i class="fa fa-check"></i><b>8.4</b> Data description</a></li>
<li class="chapter" data-level="8.5" data-path="Mersy_set_up.html"><a href="Mersy_set_up.html#open-rstudio-1"><i class="fa fa-check"></i><b>8.5</b> Open RStudio</a></li>
<li class="chapter" data-level="8.6" data-path="Mersy_set_up.html"><a href="Mersy_set_up.html#projects-and-scripts"><i class="fa fa-check"></i><b>8.6</b> Projects and Scripts</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="Mersy_set_up.html"><a href="Mersy_set_up.html#Existing_R_Projects"><i class="fa fa-check"></i><b>8.6.1</b> Using an existing R project</a></li>
<li class="chapter" data-level="8.6.2" data-path="Mersy_set_up.html"><a href="Mersy_set_up.html#creating-an-r-script-1"><i class="fa fa-check"></i><b>8.6.2</b> Creating an R script</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="Mersy_set_up.html"><a href="Mersy_set_up.html#loading-packages-1"><i class="fa fa-check"></i><b>8.7</b> Loading packages</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="mersey_three.html"><a href="mersey_three.html"><i class="fa fa-check"></i><b>9</b> Mersey III - Hydrology</a>
<ul>
<li class="chapter" data-level="9.1" data-path="mersey_three.html"><a href="mersey_three.html#task-1-flow-routing"><i class="fa fa-check"></i><b>9.1</b> Task 1: Flow routing</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="mersey_three.html"><a href="mersey_three.html#creating-a-d8-pointer"><i class="fa fa-check"></i><b>9.1.1</b> Creating a D8 pointer</a></li>
<li class="chapter" data-level="9.1.2" data-path="mersey_three.html"><a href="mersey_three.html#catchment-area"><i class="fa fa-check"></i><b>9.1.2</b> Catchment area</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="mersey_three.html"><a href="mersey_three.html#task-2-seed-points"><i class="fa fa-check"></i><b>9.2</b> Task 2: Seed points</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="mersey_three.html"><a href="mersey_three.html#seed-repositioning"><i class="fa fa-check"></i><b>9.2.1</b> Seed repositioning</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="mersey_three.html"><a href="mersey_three.html#task-3-watershed-creation"><i class="fa fa-check"></i><b>9.3</b> Task 3: Watershed creation</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="mersey_four.html"><a href="mersey_four.html"><i class="fa fa-check"></i><b>10</b> Mersey IV - Surface derivatives</a>
<ul>
<li class="chapter" data-level="10.1" data-path="mersey_four.html"><a href="mersey_four.html#task-4-reclassification"><i class="fa fa-check"></i><b>10.1</b> Task 4: Reclassification</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="mersey_four.html"><a href="mersey_four.html#land-cover"><i class="fa fa-check"></i><b>10.1.1</b> Land cover</a></li>
<li class="chapter" data-level="10.1.2" data-path="mersey_four.html"><a href="mersey_four.html#hydrology-of-soil-types-host"><i class="fa fa-check"></i><b>10.1.2</b> Hydrology of Soil Types (HOST)</a></li>
<li class="chapter" data-level="10.1.3" data-path="mersey_four.html"><a href="mersey_four.html#bedrock-geology"><i class="fa fa-check"></i><b>10.1.3</b> Bedrock geology</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="mersey_four.html"><a href="mersey_four.html#task-5-calculating-surface-derivatives"><i class="fa fa-check"></i><b>10.2</b> Task 5: Calculating surface derivatives</a></li>
<li class="chapter" data-level="10.3" data-path="mersey_four.html"><a href="mersey_four.html#task-6-extracting-surface-derivatives"><i class="fa fa-check"></i><b>10.3</b> Task 6: Extracting surface derivatives</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="mersey_four.html"><a href="mersey_four.html#water-quality-measurements"><i class="fa fa-check"></i><b>10.3.1</b> Water quality measurements</a></li>
<li class="chapter" data-level="10.3.2" data-path="mersey_four.html"><a href="mersey_four.html#spatial-areas"><i class="fa fa-check"></i><b>10.3.2</b> Spatial areas</a></li>
<li class="chapter" data-level="10.3.3" data-path="mersey_four.html"><a href="mersey_four.html#continuous-derivatives"><i class="fa fa-check"></i><b>10.3.3</b> Continuous derivatives</a></li>
<li class="chapter" data-level="10.3.4" data-path="mersey_four.html"><a href="mersey_four.html#calculating-categorical-derivatives"><i class="fa fa-check"></i><b>10.3.4</b> Calculating categorical derivatives</a></li>
<li class="chapter" data-level="10.3.5" data-path="mersey_four.html"><a href="mersey_four.html#normalising-categorical-derivatives"><i class="fa fa-check"></i><b>10.3.5</b> Normalising categorical derivatives</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="mersey_five.html"><a href="mersey_five.html"><i class="fa fa-check"></i><b>11</b> Mersey V - Statistical analysis</a>
<ul>
<li class="chapter" data-level="11.1" data-path="mersey_five.html"><a href="mersey_five.html#task-7-model-building"><i class="fa fa-check"></i><b>11.1</b> Task 7: Model building</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="mersey_five.html"><a href="mersey_five.html#an-introduction-to-linear-models-in-r"><i class="fa fa-check"></i><b>11.1.1</b> An introduction to linear models in R</a></li>
<li class="chapter" data-level="11.1.2" data-path="mersey_five.html"><a href="mersey_five.html#training-vs.-testing"><i class="fa fa-check"></i><b>11.1.2</b> Training vs. Testing</a></li>
<li class="chapter" data-level="11.1.3" data-path="mersey_five.html"><a href="mersey_five.html#variable-selection-strategies"><i class="fa fa-check"></i><b>11.1.3</b> Variable selection strategies</a></li>
<li class="chapter" data-level="11.1.4" data-path="mersey_five.html"><a href="mersey_five.html#testing-for-collinearity"><i class="fa fa-check"></i><b>11.1.4</b> Testing for collinearity</a></li>
<li class="chapter" data-level="11.1.5" data-path="mersey_five.html"><a href="mersey_five.html#stepwise-regression"><i class="fa fa-check"></i><b>11.1.5</b> Stepwise regression</a></li>
<li class="chapter" data-level="11.1.6" data-path="mersey_five.html"><a href="mersey_five.html#interpreting-results"><i class="fa fa-check"></i><b>11.1.6</b> Interpreting results</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="mersey_five.html"><a href="mersey_five.html#task-8-model-evaluation"><i class="fa fa-check"></i><b>11.2</b> Task 8: Model evaluation</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="Assessment.html"><a href="Assessment.html"><i class="fa fa-check"></i><b>12</b> Assessment</a></li>
<li class="chapter" data-level="13" data-path="Hints.html"><a href="Hints.html"><i class="fa fa-check"></i><b>13</b> Handy Hints</a>
<ul>
<li class="chapter" data-level="" data-path="Hints.html"><a href="Hints.html#dealing-with-errors-1"><i class="fa fa-check"></i>Dealing with errors</a></li>
<li class="chapter" data-level="" data-path="Hints.html"><a href="Hints.html#whitebox-functions-vs.-the-raster-package"><i class="fa fa-check"></i>Whitebox functions vs. the <code>raster</code> package</a></li>
<li class="chapter" data-level="" data-path="Hints.html"><a href="Hints.html#r-projects"><i class="fa fa-check"></i>R Projects</a></li>
<li class="chapter" data-level="" data-path="Hints.html"><a href="Hints.html#file-paths"><i class="fa fa-check"></i>File paths</a></li>
<li class="chapter" data-level="" data-path="Hints.html"><a href="Hints.html#output-files"><i class="fa fa-check"></i>Output files</a></li>
<li class="chapter" data-level="" data-path="Hints.html"><a href="Hints.html#packages-1"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="Hints.html"><a href="Hints.html#code-structure"><i class="fa fa-check"></i>Code structure</a></li>
<li class="chapter" data-level="" data-path="Hints.html"><a href="Hints.html#project_repair"><i class="fa fa-check"></i>Errors with R projects and the <code>here</code> package</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"><center><br />
Hydrological analysis in R<br />
</center></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="mersey_five" class="section level1 hasAnchor" number="11">
<h1><span class="header-section-number">Chapter 11</span> Mersey V - Statistical analysis<a href="mersey_five.html#mersey_five" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In this final chapter, we will compare the information about catchment characteristics with the water quality data collected at each of the 70 monitoring stations. To begin, load the csv file created at the end of Task 6 (<code>mersey_watersheds_ea.csv</code>), saving to a new variable called <code>watersheds_df</code>:</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="mersey_five.html#cb131-1" tabindex="-1"></a><span class="co"># Reads completed file from csv</span></span>
<span id="cb131-2"><a href="mersey_five.html#cb131-2" tabindex="-1"></a>watersheds_df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">&quot;output&quot;</span>, <span class="st">&quot;practical_2&quot;</span>, <span class="st">&quot;mersey_watersheds_ea.csv&quot;</span>))</span></code></pre></div>
<p>If you have any other variables in your R environment, these can be removed using <code>rm()</code>.</p>
<div id="task-7-model-building" class="section level2 hasAnchor" number="11.1">
<h2><span class="header-section-number">11.1</span> Task 7: Model building<a href="mersey_five.html#task-7-model-building" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This data frame should contain the following 10 water quality indicators for each watershed:</p>
<ul>
<li>pH: acidity/alkalinity;</li>
<li>SSC: suspended solids concentration (mg l<sup>−1</sup>);</li>
<li>Ca: calcium (mg l<sup>−1</sup>);</li>
<li>Mg: magnesium (mg l<sup>−1</sup>);</li>
<li>NH<sub>4</sub>: ammonium (mg-N l<sup>−1</sup>);</li>
<li>NO<sub>3</sub>: nitrate (mg-N l<sup>−1</sup>);</li>
<li>NO<sub>2</sub>: nitrite (mg-N l<sup>−1</sup>);</li>
<li>TON: total oxidised nitrogen (mg-N l<sup>−1</sup>);</li>
<li>PO<sub>4</sub>: phosphate (mg-P l<sup>−1</sup>);</li>
<li>Zn: zinc (μg l<sup>−1</sup>).</li>
</ul>
<p>It should also contain the continuous derivatives (e.g. average elevation) and categorical derivatives (e.g. land cover percentage) for each watershed.</p>
<p><strong>Note</strong>: some of your calculated percentages may not add up to 100%. In Task 4, we reclassified only the most important categorical variables. These are known to have the greatest impact of river hydrochemistry (e.g. urban areas, farmland). While other land cover categories are found within each watershed, these typically account for only a small percentage of the total area and have a limited effect on the river environment. These categories have been excluded to simplify the analysis.</p>
<div id="an-introduction-to-linear-models-in-r" class="section level3 hasAnchor" number="11.1.1">
<h3><span class="header-section-number">11.1.1</span> An introduction to linear models in R<a href="mersey_five.html#an-introduction-to-linear-models-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>It is now time to examine the relationships between river water quality and catchment metrics. The key model outputs that are ultimately required for the assessment are:</p>
<ol style="list-style-type: decimal">
<li><p>Regression equations for each water quality variable (dependent variable; n = 10) and the key explanatory catchment characteristics (independent variables; n = 16).</p></li>
<li><p>Associated model values (R<sup>2</sup>, <em>p</em> value).</p></li>
</ol>
<blockquote>
<p>Remember, you don’t have to run every code block shown below, but you can do so if it would help your understanding.</p>
</blockquote>
<p>The simplest way to run a linear regression in R is to use the <code>lm()</code> function, an example of which is shown below, storing the output in <code>model</code> (you can change this name to reflect the input variables):</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="mersey_five.html#cb132-1" tabindex="-1"></a><span class="co"># Fits a linear model</span></span>
<span id="cb132-2"><a href="mersey_five.html#cb132-2" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> Zn <span class="sc">~</span> average_elevation, <span class="at">data =</span> watersheds_df)</span></code></pre></div>
<p>We have defined the data frame being used (<code>data = watersheds_df</code>) and the input variables from that data frame. This is achieved by including their column names, shown here:</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="mersey_five.html#cb133-1" tabindex="-1"></a><span class="fu">colnames</span>(watersheds_df)</span></code></pre></div>
<pre><code>##  [1] &quot;Seed_Point_ID&quot;          &quot;FID&quot;                    &quot;EA_ID&quot;                 
##  [4] &quot;Group&quot;                  &quot;Ph&quot;                     &quot;SSC&quot;                   
##  [7] &quot;Ca&quot;                     &quot;Mg&quot;                     &quot;NH4&quot;                   
## [10] &quot;NO3&quot;                    &quot;NO2&quot;                    &quot;TON&quot;                   
## [13] &quot;PO4&quot;                    &quot;Zn&quot;                     &quot;area&quot;                  
## [16] &quot;count&quot;                  &quot;average_elevation&quot;      &quot;average_rainfall&quot;      
## [19] &quot;average_slope&quot;          &quot;average_aspect&quot;         &quot;Arable&quot;                
## [22] &quot;Heath&quot;                  &quot;Grassland&quot;              &quot;Urban&quot;                 
## [25] &quot;Wetland&quot;                &quot;Permeable&quot;              &quot;Impermeable&quot;           
## [28] &quot;Gleyed&quot;                 &quot;Peats&quot;                  &quot;Sands_and_Muds&quot;        
## [31] &quot;Limestone&quot;              &quot;Coal&quot;                   &quot;Arable_percent&quot;        
## [34] &quot;Heath_percent&quot;          &quot;Grassland_percent&quot;      &quot;Urban_percent&quot;         
## [37] &quot;Wetland_percent&quot;        &quot;Permeable_percent&quot;      &quot;Impermeable_percent&quot;   
## [40] &quot;Gleyed_percent&quot;         &quot;Peats_percent&quot;          &quot;Sands_and_Muds_percent&quot;
## [43] &quot;Limestone_percent&quot;      &quot;Coal_percent&quot;</code></pre>
<p>Input variables in the <strong>formula</strong> are separated by <code>~</code>, where the variable to the left is the dependent variable (<code>Zn</code>) and the variable to the right is an independent variable (<code>average_elevation</code>). We can, however, include <strong>multiple</strong> independent variables to perform multiple linear regression. This is achieved as follows, where additional independent variables are separated by <code>+</code>:</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="mersey_five.html#cb135-1" tabindex="-1"></a><span class="co"># Fits a linear model</span></span>
<span id="cb135-2"><a href="mersey_five.html#cb135-2" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> Zn <span class="sc">~</span> average_elevation <span class="sc">+</span> Grassland_percent, <span class="at">data =</span> watersheds_df)</span></code></pre></div>
<p>We can then assess the model output using the <code>summary</code> function:</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="mersey_five.html#cb136-1" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Zn ~ average_elevation + Grassland_percent, data = watersheds_df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -17.358  -8.324  -3.055   3.915  43.884 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       33.55321    3.41959   9.812 1.37e-14 ***
## average_elevation -0.02018    0.01179  -1.712  0.09156 .  
## Grassland_percent -0.22543    0.06846  -3.293  0.00159 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 11.86 on 67 degrees of freedom
## Multiple R-squared:  0.2415, Adjusted R-squared:  0.2189 
## F-statistic: 10.67 on 2 and 67 DF,  p-value: 9.512e-05</code></pre>
<p>For this set of independent variables, we have an R<sup>2</sup> of 0.24 (<code>Multiple R-squared: 0.2415</code>) and a model <em>p</em> value of &lt; 0.01 (<code>p-value: 9.512e-05</code>).</p>
<p>The model coefficients for the independent variables are described above, where <code>*</code> denotes <em>p</em> values &lt; 0.05 (95% probability) and <code>**</code> denotes <em>p</em> values &lt; 0.01 (99% probability). As the coefficients are very small, they are presented in scientific notation. These can be converted to numeric (non-scientific) format using the following code:</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="mersey_five.html#cb138-1" tabindex="-1"></a><span class="fu">format</span>(<span class="sc">-</span><span class="fl">2.096e-04</span>, <span class="at">scientific =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] &quot;-0.0002096&quot;</code></pre>
<p>We can supply multiple values to the <code>format</code> function by creating a vector:</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="mersey_five.html#cb140-1" tabindex="-1"></a><span class="fu">format</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="fl">2.096e-04</span>, <span class="sc">-</span><span class="fl">8.358e-06</span>, ...) , <span class="at">scientific =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<blockquote>
<p>When you’re happy you understanding the formatting of the <code>lm</code> function, move on to the next section.</p>
</blockquote>
</div>
<div id="training-vs.-testing" class="section level3 hasAnchor" number="11.1.2">
<h3><span class="header-section-number">11.1.2</span> Training vs. Testing<a href="mersey_five.html#training-vs.-testing" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>One limitation of the above approach is that our dataframe (<code>watersheds_df</code>) contains observations from all 70 EA monitoring stations.</p>
<p>When performing statistical analysis, it is common practice to split any dataset into:</p>
<ul>
<li>a <strong>training</strong> subset, which is used to create the model(s).</li>
<li>a <strong>testing</strong> subset, which is used to evaluate the model(s).</li>
</ul>
<p>Subsetting our data in this way allows models to be evaluated more rigorously. Many models perform well “in-sample” but poorly “out-of-sample” when evaluated against independent data (i.e. the testing subset). This is commonly referred to as “over-fitting”.</p>
<p>Training and testing subsets are usually defined randomly, with an approximate ratio of 70:30 (although this varies). However, and to ensure reproducibility, this step has been completed for you: the <code>watersheds_df</code> dataframe contains a <code>group</code> variable denoting which monitoring sites belong to the training and testing subsets.</p>
<blockquote>
<p>Run the code above to create <code>training</code> and <code>testing</code> dataframes:</p>
</blockquote>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="mersey_five.html#cb141-1" tabindex="-1"></a><span class="co"># Extracts training dataset, comprising 50 observations (~70%)</span></span>
<span id="cb141-2"><a href="mersey_five.html#cb141-2" tabindex="-1"></a>training <span class="ot">&lt;-</span> <span class="fu">subset</span>(watersheds_df, Group <span class="sc">==</span> <span class="st">&quot;Training&quot;</span>)</span>
<span id="cb141-3"><a href="mersey_five.html#cb141-3" tabindex="-1"></a></span>
<span id="cb141-4"><a href="mersey_five.html#cb141-4" tabindex="-1"></a><span class="co"># Extracts training dataset, comprising 20 observations (~30%)</span></span>
<span id="cb141-5"><a href="mersey_five.html#cb141-5" tabindex="-1"></a>testing <span class="ot">&lt;-</span> <span class="fu">subset</span>(watersheds_df, Group <span class="sc">==</span> <span class="st">&quot;Testing&quot;</span>) </span></code></pre></div>
<blockquote>
<p>Before you move on to the next section, can you think of any limitations of this approach?</p>
</blockquote>
<blockquote>
<p>Hints: How important is the training-testing ratio? How are training-testing subsets created?</p>
</blockquote>
</div>
<div id="variable-selection-strategies" class="section level3 hasAnchor" number="11.1.3">
<h3><span class="header-section-number">11.1.3</span> Variable selection strategies<a href="mersey_five.html#variable-selection-strategies" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>An addition weakness of the above approach is that we have manually defined the independent variables of interest (<code>average_elevation + Grassland_percent</code>). For exploratory analysis, however, we may not know which are the most important variables. Perhaps there is a combination of independent variables which produces a better model fit (e.g. R<sup>2</sup> &gt; 0.24)?</p>
<p>Determining which variables to include/exclude from a model is a very difficult problem, which has resulted in many different variable selection strategies. Common approaches include expert opinion and/or theory, partial least squares (PLS) regression, implemented in <code>PLS</code>, Least Absolute Shrinkage and Selection Operator (LASSO), implemented in <code>glmnet</code> and <code>LARS</code>, as well as elastic net methods and ridge regression, also implemented in <code>glmnet</code>. You may want to explore some of these more complex approaches for your dissertation.</p>
<p>For our analysis, we are going to use a relatively simple method known as <strong>Stepwise Regression</strong>, implemented in the <code>MASS</code> package. This works by including <strong>all</strong> the relevant independent variables in the analysis and then selecting those with the greatest explanatory power.</p>
<p>However, we don’t necessarily want to test <em>all</em> model variables. We would probably want to exclude the categorical counts (e.g. <code>Arable</code>, <code>Heath</code>, …) as these factors are already represented by the normalised variables (e.g. <code>Arable_percent</code>, <code>Heath_percent</code>, …), as well as any IDs or geometry variables (<code>area</code>). In general, we are only interested in testing the continuous derivatives (column names starting with <code>average_</code>) and the normalised categorical derivatives (column names ending in <code>_percent</code>).</p>
<p>Rather than typing out the columns of interest manually, we are going to use the <code>select</code> function from the <code>dplyr</code> package to do so:</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="mersey_five.html#cb142-1" tabindex="-1"></a><span class="co"># Creates a vector of column names, including only those which contain &quot;average&quot; or &quot;percent&quot;</span></span>
<span id="cb142-2"><a href="mersey_five.html#cb142-2" tabindex="-1"></a>factors <span class="ot">&lt;-</span> <span class="fu">colnames</span>(watersheds_df <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="fu">contains</span>(<span class="fu">c</span>(<span class="st">&quot;average&quot;</span>, <span class="st">&quot;percent&quot;</span>))))</span>
<span id="cb142-3"><a href="mersey_five.html#cb142-3" tabindex="-1"></a></span>
<span id="cb142-4"><a href="mersey_five.html#cb142-4" tabindex="-1"></a><span class="co"># Prints to console</span></span>
<span id="cb142-5"><a href="mersey_five.html#cb142-5" tabindex="-1"></a>factors</span></code></pre></div>
<pre><code>##  [1] &quot;average_elevation&quot;      &quot;average_rainfall&quot;       &quot;average_slope&quot;         
##  [4] &quot;average_aspect&quot;         &quot;Arable_percent&quot;         &quot;Heath_percent&quot;         
##  [7] &quot;Grassland_percent&quot;      &quot;Urban_percent&quot;          &quot;Wetland_percent&quot;       
## [10] &quot;Permeable_percent&quot;      &quot;Impermeable_percent&quot;    &quot;Gleyed_percent&quot;        
## [13] &quot;Peats_percent&quot;          &quot;Sands_and_Muds_percent&quot; &quot;Limestone_percent&quot;     
## [16] &quot;Coal_percent&quot;</code></pre>
<blockquote>
<p>Run the above code. <strong>Note</strong>, the formatting of <code>dplyr::select</code> may be slightly confusing but it is necessary because there is also a <code>select</code> function in the <code>MASS</code> package. Here, we are telling R to use <code>select</code> from <code>dplyr</code>.</p>
</blockquote>
<p>Using this vector of column names, we are going to create a new data frame (called <code>variables</code>) containing only the independent variables of interest. <strong>Crucially</strong>, this is only for the <code>training</code> dataset:</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="mersey_five.html#cb144-1" tabindex="-1"></a>variables <span class="ot">&lt;-</span> training[factors]</span></code></pre></div>
<blockquote>
<p>Run the above code and use <code>head()</code> to inspect the results.</p>
</blockquote>
</div>
<div id="testing-for-collinearity" class="section level3 hasAnchor" number="11.1.4">
<h3><span class="header-section-number">11.1.4</span> Testing for collinearity<a href="mersey_five.html#testing-for-collinearity" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Before we use this dataset to investigate the controls on water quality, it is a good idea to test for <strong>collinearity</strong>, which occurs when independent variables in our regression model are highly correlated to each other. This is a common problem in regression analysis. If you are interested in the factors which influence <span class="math inline">\(A\)</span>, you might perform a regression involving <span class="math inline">\(B\)</span> and <span class="math inline">\(C\)</span>. However, if <span class="math inline">\(B\)</span> and <span class="math inline">\(C\)</span> are highly correlated (as <span class="math inline">\(B\)</span> increases, so too does <span class="math inline">\(C\)</span>), how do you know which is important?</p>
<p>To test for this, we can create a <strong>correlation matrix</strong>, using the <code>cor</code> function available in the base R <code>stats</code> package, and then visualise this using the <code>corrplot()</code> function from the <code>corrplot</code> package:</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="mersey_five.html#cb145-1" tabindex="-1"></a><span class="co"># Create correlation matrix</span></span>
<span id="cb145-2"><a href="mersey_five.html#cb145-2" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(variables)</span>
<span id="cb145-3"><a href="mersey_five.html#cb145-3" tabindex="-1"></a></span>
<span id="cb145-4"><a href="mersey_five.html#cb145-4" tabindex="-1"></a><span class="co"># Visualise using corrplot()</span></span>
<span id="cb145-5"><a href="mersey_five.html#cb145-5" tabindex="-1"></a><span class="fu">corrplot</span>(cor_matrix, <span class="at">method =</span> <span class="st">&#39;circle&#39;</span>, </span>
<span id="cb145-6"><a href="mersey_five.html#cb145-6" tabindex="-1"></a>         <span class="at">type =</span> <span class="st">&#39;lower&#39;</span>, <span class="at">diag =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="Practical_1_files/figure-html/unnamed-chunk-153-1.png" width="672" style="display: block; margin: auto;" /></p>
<blockquote>
<p>You can modify the design to show additional information, such as using <code>method = 'number'</code> to include the correlation values (1 = perfect positive correlation, 0 = no correlation, -1 = perfect negative correlation). Further information available <a href="https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html">here</a></p>
</blockquote>
<p>Overall, we can see evidence of clear collinearity, in particular <strong>between the topographic variables</strong>, with high positive correlations between <code>average_slope</code>, <code>average_elevation</code> and <code>average_rainfall</code>. This reflects the fact that the higher elevation catchments on the periphery of the Mersey Basin tend to be steeper and wetter (i.e., <em>orographic rainfall</em>) than their low elevation counterparts. Fundamentally, these different variables are closely related, so including them all in the model means we are double- or triple-counting the effects of topography.</p>
<p>In addition, we can also see evidence of collinearity with <strong>other catchment characteristics</strong>. For example, <code>average_slope</code> is negatively correlated with the proportion of arable and urban land, and positively correlated with wetland, heath and peat coverage.</p>
<blockquote>
<p>Can you think why we might see the above pattern?</p>
</blockquote>
<p>We can also see evidence of high collinearity between <code>Coal</code> and <code>Sands_and_Muds</code>, which reflects their spatial distribution across the basin. You could visualise this by plotting the <a href="https://emm-concepts.com/mersey_four.html#bedrock-geology">bedrock raster</a> you created in Mersey IV. As there are only three bedrock categories, and limestone is rare, high coverage of <code>Coal</code> has to be associated with low coverage of <code>Sands_and_Muds</code> (and vice versa).</p>
<p>Based on the above reasoning, we can be justified in <strong>removing variables</strong> with evidence of collinearity (<code>average_slope</code>, <code>average_elevation</code>, <code>average_rainfall</code>, <code>Coal</code>). We can achieve this using the <code>select</code> function from the <code>dplyr</code> package, which we used previously, but modified slightly to exclude variables, rather than retain them:</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="mersey_five.html#cb146-1" tabindex="-1"></a><span class="co"># Remove colinear variables</span></span>
<span id="cb146-2"><a href="mersey_five.html#cb146-2" tabindex="-1"></a>variables <span class="ot">&lt;-</span> variables <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span><span class="fu">contains</span>(<span class="fu">c</span>(<span class="st">&quot;slope&quot;</span>, <span class="st">&quot;rainfall&quot;</span>, <span class="st">&quot;elevation&quot;</span>, <span class="st">&quot;Coal&quot;</span>)))</span></code></pre></div>
<blockquote>
<p>Run the above to remove collinear variables. You may want to produce a new correlation matrix (<code>corrplot()</code>) to investigate the effects.</p>
</blockquote>
</div>
<div id="stepwise-regression" class="section level3 hasAnchor" number="11.1.5">
<h3><span class="header-section-number">11.1.5</span> Stepwise regression<a href="mersey_five.html#stepwise-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>With our new <em>filtered</em> dataset, we can now combine this data frame (<code>cbind</code>) with a dependent variable of interest; we will use zinc (Zn) as an example. Our new dataframe will be called <code>model_df</code> as it contains all the variables (dependent + independent) required for multiple linear regression. <strong>Note</strong>: by default, <code>cbind</code> will (somewhat unhelpfully) rename input column names e.g. <code>Zn</code> will become <code>watersheds_df$Zn</code>. The code below specifies the new column name as Zn (<code>Zn =</code>) for readability:</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="mersey_five.html#cb147-1" tabindex="-1"></a><span class="co"># Column bind the Zn column with the independent variables from the training dataset</span></span>
<span id="cb147-2"><a href="mersey_five.html#cb147-2" tabindex="-1"></a>model_df <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="at">Zn =</span> training<span class="sc">$</span>Zn, variables)</span></code></pre></div>
<p>When complete, we can then run a new model, making sure to update the data frame used (<code>data = model_df</code>) and updating the formula to <code>Zn ~ .</code>. This denotes that <em>all</em> other data frame columns will be included as independent variables (a useful time saver!):</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="mersey_five.html#cb148-1" tabindex="-1"></a><span class="co"># Fits a linear model, including all other columns (~.) as independent variables</span></span>
<span id="cb148-2"><a href="mersey_five.html#cb148-2" tabindex="-1"></a>zn_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> Zn <span class="sc">~</span> ., <span class="at">data =</span> model_df)</span></code></pre></div>
<blockquote>
<p>When you’re happy you understand the <code>lm</code> syntax, combine the two dataframes, run the linear model and inspect the output using <code>summary()</code>. This should resemble the following:</p>
</blockquote>
<pre><code>## 
## Call:
## lm(formula = Zn ~ ., data = model_df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -14.651  -5.609  -1.941   2.340  32.979 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)            -1.051e+02  4.517e+02  -0.233 0.817329    
## average_aspect         -4.239e-02  5.120e-02  -0.828 0.412966    
## Arable_percent          5.030e-01  2.635e-01   1.909 0.064073 .  
## Heath_percent           7.310e-01  3.115e-01   2.347 0.024407 *  
## Grassland_percent       4.870e-01  2.629e-01   1.853 0.071926 .  
## Urban_percent           1.045e+00  2.820e-01   3.704 0.000689 ***
## Wetland_percent         4.388e-01  2.738e-01   1.603 0.117540    
## Permeable_percent       7.853e-01  4.580e+00   0.171 0.864798    
## Impermeable_percent     1.588e-01  4.592e+00   0.035 0.972608    
## Gleyed_percent          7.545e-01  4.578e+00   0.165 0.869991    
## Peats_percent           8.370e-01  4.594e+00   0.182 0.856443    
## Sands_and_Muds_percent  1.126e-03  5.797e-02   0.019 0.984603    
## Limestone_percent       1.681e-02  3.198e-01   0.053 0.958354    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 11.14 on 37 degrees of freedom
## Multiple R-squared:  0.5143, Adjusted R-squared:  0.3568 
## F-statistic: 3.265 on 12 and 37 DF,  p-value: 0.002776</code></pre>
<p>Our overall model fit (R<sup>2</sup>) is <span class="math inline">\(0.5143\)</span> which indicates that the independent variables explain ~51% of variability in the dependent variable. Our model is statistically significant, here defined as having a <em>p</em> value &lt; 0.05. When values are very small (e.g. <em>p</em> &lt; 0.0005), we would typically present these as a discrete value e.g. <em>p</em> &lt; 0.05, &lt; 0.01, &lt; 0.001. Generally, we only use models in which we can be 95% confident or higher (i.e. significance level of 0.05 or less).</p>
<p>However, it is important to note that <em>p</em> values should be not be considered in isolation and need to be interpreted carefully. For statistical reviews of using and interpreting <em>p</em> values, see <span class="citation">Goodman (<a href="#ref-goodman_dirty_2008">2008</a>)</span> and <span class="citation">Andrade (<a href="#ref-andrade_p_2019">2019</a>)</span>. For a broader overview, see the <em>Nature</em> commentary by <span class="citation">Amrhein <em>et al.</em> (<a href="#ref-amrhein_scientists_2019">2019</a>)</span>, as well as a summary article by <a href="https://www.vox.com/latest-news/2019/3/22/18275913/statistical-significance-p-values-explained">Vox</a>.</p>
<p>In addition, while the model is significant, it contains <strong>all the independent variables</strong>, some of which probably have no effect on Zinc concentrations. We can filter out unimportant variables using the <code>step.AIC</code> function from the <code>MASS</code> library:</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="mersey_five.html#cb150-1" tabindex="-1"></a><span class="co"># Stepwise regression model</span></span>
<span id="cb150-2"><a href="mersey_five.html#cb150-2" tabindex="-1"></a>step.model <span class="ot">&lt;-</span> <span class="fu">stepAIC</span>(zn_model, <span class="co"># Input linear model</span></span>
<span id="cb150-3"><a href="mersey_five.html#cb150-3" tabindex="-1"></a>                      <span class="at">direction =</span> <span class="st">&quot;both&quot;</span>,</span>
<span id="cb150-4"><a href="mersey_five.html#cb150-4" tabindex="-1"></a>                      <span class="at">trace =</span> <span class="cn">FALSE</span>, <span class="co"># Print out intermediate results? </span></span>
<span id="cb150-5"><a href="mersey_five.html#cb150-5" tabindex="-1"></a>                      <span class="at">scope =</span> <span class="cn">NULL</span>, </span>
<span id="cb150-6"><a href="mersey_five.html#cb150-6" tabindex="-1"></a>                      <span class="at">k =</span> <span class="dv">2</span>) </span></code></pre></div>
<p>Helpfully, this takes the output of the <code>lm</code> model (<code>zn_model</code>) with no need for any additional data wrangling. The following are important parameters:</p>
<ul>
<li><code>direction = "both"</code>:
<ul>
<li>Determines the method used, either <strong>forward</strong> or <strong>backward</strong> stepwise regression, or a mixture of <strong>both</strong>.</li>
<li>“Forward” begins with a model with <strong>no</strong> variables and then starts adding the most significant variables, stopping when there are no more significant variables.</li>
<li>“Backward” begins with a model with <strong>all</strong> variables and then starts removing the least significant variables, stopping when only significant variables are remaining.</li>
<li>“Both” includes both of the above, allowing for variables to be added/removed at each step.</li>
</ul></li>
<li><code>scope</code>:
<ul>
<li>Defines the range of models examined in the stepwise search (currently set to <code>NULL</code>).</li>
</ul></li>
<li><code>k = 2</code>:
<ul>
<li>The number of degrees of freedom used for the penalty i.e. for determining whether variables are significant or not. Although any value can be used here, it is typical to use either <span class="math inline">\(k = 2\)</span>, which is equivalent to the Akaike information criterion (AIC), or <span class="math inline">\(k = log(n)\)</span>, which is equivalent to the Bayesian information criterion (BIC), where <code>n</code> is the number of data points in the model (<span class="math inline">\(n = 50\)</span>). Both the AIC and BIC can be used to assess the relative quality of statistical models.</li>
</ul></li>
</ul>
<blockquote>
<p>Run the above model (<code>direction = "both"</code> and <code>k = 2</code>) and print the output using <code>summary()</code>:</p>
</blockquote>
<pre><code>## 
## Call:
## lm(formula = Zn ~ Arable_percent + Heath_percent + Grassland_percent + 
##     Urban_percent + Wetland_percent + Permeable_percent + Gleyed_percent + 
##     Peats_percent, data = model_df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.873  -5.535  -2.071   3.257  33.422 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       -102.2893    44.3771  -2.305 0.026303 *  
## Arable_percent       0.5686     0.2330   2.441 0.019061 *  
## Heath_percent        0.7006     0.2849   2.459 0.018242 *  
## Grassland_percent    0.4910     0.2349   2.090 0.042815 *  
## Urban_percent        1.0569     0.2597   4.069 0.000209 ***
## Wetland_percent      0.4388     0.2527   1.737 0.089966 .  
## Permeable_percent    0.6677     0.3972   1.681 0.100341    
## Gleyed_percent       0.6332     0.3923   1.614 0.114250    
## Peats_percent        0.7313     0.4086   1.790 0.080837 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.68 on 41 degrees of freedom
## Multiple R-squared:  0.5051, Adjusted R-squared:  0.4086 
## F-statistic: 5.231 on 8 and 41 DF,  p-value: 0.0001532</code></pre>
<p>As you can see above, we have now produced a more parsimonious model, but there are still many independent variables (<span class="math inline">\(n = 8\)</span>), some of which might be less important. We can address this in a few ways:</p>
<ol style="list-style-type: decimal">
<li><p>Use a more strict criteria for determining significance i.e., shifting from AIC (<code>k = 2</code>) to BIC (<code>k = log(n)</code>)</p></li>
<li><p>Updating the model <code>scope</code>, which defines the range of models examined in the stepwise search. Rather than, for example, building from an <em>empty</em> model and progressively adding variables (i.e., <code>direction = "forward"</code>), we can give stepwise a headstart by performing the stepwise search <em>from an initial model</em>.</p></li>
</ol>
<p>To achieve this, we are going to use the <code>ols_step_all_possible()</code> function from the <code>oslrr</code> package, which takes a linear model and fits all possible regressions. For a model with three independent variables (<span class="math inline">\(A, B, C\)</span>), this would include <strong>six</strong> models: <span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span> and <span class="math inline">\(C\)</span> alone, <span class="math inline">\(A+B\)</span>, <span class="math inline">\(A+C\)</span> and <span class="math inline">\(B+C\)</span>. As the number of independent variables (<span class="math inline">\(k\)</span>) increases, the number of possible combinations increases by a factor of <span class="math inline">\(2^k\)</span>. For our reduced dataset, this is equivalent to <span class="math inline">\(2^{12}\)</span> which is <span class="math inline">\(4096\)</span> possible models!</p>
<p>In this case, we are going to use <code>ols_step_all_possible()</code> to perform <strong>univariable</strong> linear regression, which is achieved by setting <code>max_order = 1</code>, and utilising the <strong>full model</strong> in the calculation:</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="mersey_five.html#cb152-1" tabindex="-1"></a><span class="co"># Perform univariable regression for all independent variables</span></span>
<span id="cb152-2"><a href="mersey_five.html#cb152-2" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="fu">ols_step_all_possible</span>(zn_model, <span class="at">max_order =</span> <span class="dv">1</span>)</span>
<span id="cb152-3"><a href="mersey_five.html#cb152-3" tabindex="-1"></a></span>
<span id="cb152-4"><a href="mersey_five.html#cb152-4" tabindex="-1"></a><span class="co"># Print summary</span></span>
<span id="cb152-5"><a href="mersey_five.html#cb152-5" tabindex="-1"></a><span class="fu">print</span>(k)</span></code></pre></div>
<pre><code>##    Index N             Predictors    R-Square Adj. R-Square  Mallow&#39;s Cp
## 5      1 1          Urban_percent 0.364259451  0.3510148559  0.293201616
## 4      2 1      Grassland_percent 0.174429003  0.1572296068  0.083658529
## 9      3 1         Gleyed_percent 0.104383030  0.0857243436  0.022395861
## 7      4 1      Permeable_percent 0.067827513  0.0484072532 -0.004844245
## 1      5 1         average_aspect 0.027677488  0.0074207688 -0.078097077
## 6      6 1        Wetland_percent 0.021903272  0.0015262568 -0.030741536
## 10     7 1          Peats_percent 0.020526736  0.0001210431 -0.052335619
## 2      8 1         Arable_percent 0.014586856 -0.0059425843 -0.097833833
## 8      9 1    Impermeable_percent 0.004774494 -0.0159593704 -0.103020493
## 12    10 1      Limestone_percent 0.003867060 -0.0168857093         -Inf
## 11    11 1 Sands_and_Muds_percent 0.003466858 -0.0172942487 -0.075015980
## 3     12 1          Heath_percent 0.002184144 -0.0186036866 -0.057947143</code></pre>
<blockquote>
<p>Run the above code to produce univariable regressions. You can modify <code>max_order</code> to investigate different combinations of variables, although this will increase the code run time. Remember to set <code>max_order</code> back to <span class="math inline">\(1\)</span> for subsequent analysis.</p>
</blockquote>
<p>Based on the above approach, we can evaluate the relative performance of the different models using R<sup>2</sup>, adjusted R<sup>2</sup>, and other criteria. The best performing univariable model utilises <code>Urban_percent</code>, with an R<sup>2</sup> of <span class="math inline">\(~0.36\)</span>. As the best explanatory variable, we are going to use this as the starting point for our new stepwise search.</p>
<p>The code below is very similar to our previous use of stepwise, but this time includes the more strict <strong>BIC</strong> threshold for determining significance (<code>k = log(n)</code>), and utilises the <code>scope</code> argument to define the start point for the search (<code>lower = ~Urban_percent</code>) and the potential end point (<code>upper = ~zn_model</code>).</p>
<p><strong>To summarise</strong>, we are starting with a simple univariable model, in which zinc concentrations are solely related to the urban land cover percentage, and then progressively searching through other combinations of models, adding or removing variables (<code>direction = "both"</code>), to find the best outcome. The quality of models is assessed by BIC, which evaluates model fit while penalising unnecessary variables. The upper limit is the model containing <strong>all</strong> the variables (<code>upper = ~zn_model</code>), and while this would have the highest model fit (R<sup>2</sup>), it is likely to have unnecessary variables and would be excluded based on BIC.</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="mersey_five.html#cb154-1" tabindex="-1"></a><span class="co"># Updated stepwise regression model, using BIC and scope</span></span>
<span id="cb154-2"><a href="mersey_five.html#cb154-2" tabindex="-1"></a>step.model <span class="ot">&lt;-</span> <span class="fu">stepAIC</span>(zn_model, <span class="co"># Input linear model</span></span>
<span id="cb154-3"><a href="mersey_five.html#cb154-3" tabindex="-1"></a>                      <span class="at">direction =</span> <span class="st">&quot;both&quot;</span>,</span>
<span id="cb154-4"><a href="mersey_five.html#cb154-4" tabindex="-1"></a>                      <span class="at">trace =</span> <span class="cn">FALSE</span>, </span>
<span id="cb154-5"><a href="mersey_five.html#cb154-5" tabindex="-1"></a>                      <span class="co"># Utilising the scope argument</span></span>
<span id="cb154-6"><a href="mersey_five.html#cb154-6" tabindex="-1"></a>                      <span class="at">scope =</span> <span class="fu">list</span>(<span class="at">lower =</span> <span class="sc">~</span>Urban_percent, <span class="at">upper =</span> zn_model), </span>
<span id="cb154-7"><a href="mersey_five.html#cb154-7" tabindex="-1"></a>                      <span class="co"># Utilising the more strict BIC [k = log(n)], rather than AIC [k = 2]</span></span>
<span id="cb154-8"><a href="mersey_five.html#cb154-8" tabindex="-1"></a>                      <span class="at">k =</span> <span class="fu">log</span>(<span class="fu">nrow</span>(training)))</span>
<span id="cb154-9"><a href="mersey_five.html#cb154-9" tabindex="-1"></a></span>
<span id="cb154-10"><a href="mersey_five.html#cb154-10" tabindex="-1"></a><span class="co"># Print summary</span></span>
<span id="cb154-11"><a href="mersey_five.html#cb154-11" tabindex="-1"></a><span class="fu">summary</span>(step.model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Zn ~ Urban_percent, data = model_df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -17.217  -6.032  -3.555   6.269  40.717 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   11.31283    2.28486   4.951 9.52e-06 ***
## Urban_percent  0.43389    0.08274   5.244 3.49e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 11.19 on 48 degrees of freedom
## Multiple R-squared:  0.3643, Adjusted R-squared:  0.351 
## F-statistic:  27.5 on 1 and 48 DF,  p-value: 3.491e-06</code></pre>
<blockquote>
<p>Run the above code, making sure you understanding the effects of <code>k</code> and <code>scope</code>.</p>
</blockquote>
</div>
<div id="interpreting-results" class="section level3 hasAnchor" number="11.1.6">
<h3><span class="header-section-number">11.1.6</span> Interpreting results<a href="mersey_five.html#interpreting-results" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Our original model, based upon 12 independent variables, had an R<sup>2</sup> of 0.514. Our second model, using a simple stepwise regression (<code>k = 2</code>, <code>scope = NULL</code>), produced a similar output (R<sup>2</sup> = 0.505), with a reduced but still sizeable number of independent variables. Our final model, employing a more strict threshold for significance (<code>k = log(n)</code>) and a starting point for the stepwise search, produced an extremely parsimonious model, with just one independent variable, but at the cost of a reduction in model fit (R<sup>2</sup> = 0.364).</p>
<p>These results raise an important question: <strong>how should model parsimony be weighted against model performance?</strong></p>
<p>This is a question you will have to answer in your own research, as you select a model from a suite of options and <a href="https://www.poetryfoundation.org/poems/44272/the-road-not-taken">exclude others</a>.</p>
<p>In general, we prefer models with the minimum number of parameters (independent variables), so for our subsequent analysis, we will follow the ‘strict’ approach outlined above. These models require fewer assumptions, less intensive data collection, can be applied more confidently to new data sets/locations, and are often easier to interpret. This principle of model parsimony is based upon <strong>Occam’s Razor</strong>: “other things being equal, simpler explanations are generally better than more complex ones”.</p>
<p>Our model coefficients are now as follows:</p>
<ul>
<li><code>intercept</code> = 11.31283, <em>p</em> = 9.52e-06 (<em>p</em> &lt; 0.01)</li>
<li><code>Urban_percent</code> = 0.43389, <em>p</em> = 3.49e-06 (<em>p</em> &lt; 0.01)</li>
</ul>
<p>Coefficients are important because they are used in <strong>regression equations</strong>, which can then be used to predict values.</p>
<p>The general format for a regression equation is as follows:</p>
<p><span class="math display">\[
y = a + (b_1 \cdot x_1) + (b_2 \cdot x_2) + (b_n \cdot x_n)
\]</span>
where <code>a</code> is the constant (intercept) value, and <code>b</code> is the coefficient of x.</p>
<p>For our Zn model above, we can define our regression equation (presented using sensible data precision) as:</p>
<p><span class="math display">\[
Zn = 11.31 + (0.43 \cdot Urban \: percent)
\]</span>
<strong>Well done!</strong> You have now calculated a regression which links the dependent variable (Zn) to an independent variable, in this case the percentage of urban land cover.</p>
<blockquote>
<p>For your assessment, we would like you to <strong>explain</strong> the regression results, linking to hydrological processes and literature. Think about specific sources of pollution, transport pathways, types of flow…</p>
</blockquote>
</div>
</div>
<div id="task-8-model-evaluation" class="section level2 hasAnchor" number="11.2">
<h2><span class="header-section-number">11.2</span> Task 8: Model evaluation<a href="mersey_five.html#task-8-model-evaluation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Having created a statistical model, it is necessary to evaluate its performance. Comparison plots of <strong>measured vs. modelled (or predicted) values</strong> are one common way to assess model quality, alongside other metrics such as root-mean-square error (RMSE), normalised root-mean-square-error (nRMSE), Q-Q plots, or histograms of model residuals. You may want to explore some of these for the assessment.</p>
<p>To calculate modelled values, we can use the <code>predict()</code> function, taking the model variable (<code>step.model</code>) as the input, rather than re-creating the above equation manually in code, and using our <code>testing</code> dataframe for the <code>newdata</code> argument:</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="mersey_five.html#cb156-1" tabindex="-1"></a><span class="co"># Predict Zn values based upon stepwise model, saving to testing dataframe</span></span>
<span id="cb156-2"><a href="mersey_five.html#cb156-2" tabindex="-1"></a>testing<span class="sc">$</span>predicted_Zn <span class="ot">&lt;-</span> <span class="fu">predict</span>(step.model, <span class="at">newdata =</span> testing)</span></code></pre></div>
<p>If<code>new_data</code> is not defined, the <code>predict</code> function uses the fitted values for prediction i.e. the training data used to construct the model (see <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/predict.lm">here</a>).</p>
<blockquote>
<p>Run the above code block to predict Zn concentrations in the testing dataset, based on the regression model produced from the training dataset.</p>
</blockquote>
<p>These values could be used to calculate RMSE or other metrics (nRMSE) using your own code or additional packages (e.g. <code>Metrics</code>);</p>
<p><span class="math display">\[
RMSE = \sqrt{mean(measured\:values - modelled\:values)^2}
\]</span></p>
<p>Plots of measured vs. modelled values (as well as Q-Q plots and histograms) can be created in ggplot2. Here is an example:</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="mersey_five.html#cb157-1" tabindex="-1"></a><span class="co"># ggplot of measured vs. modelled (predicted) NO2 values</span></span>
<span id="cb157-2"><a href="mersey_five.html#cb157-2" tabindex="-1"></a>zn_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> testing, <span class="fu">aes</span>(<span class="at">x =</span> Zn, <span class="at">y =</span> predicted_Zn)) <span class="sc">+</span></span>
<span id="cb157-3"><a href="mersey_five.html#cb157-3" tabindex="-1"></a>  <span class="co"># Adding a linear regression (&quot;lm&quot;), removing standard error bars (se = FALSE)</span></span>
<span id="cb157-4"><a href="mersey_five.html#cb157-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">colour=</span><span class="st">&quot;#FF953C&quot;</span>) <span class="sc">+</span></span>
<span id="cb157-5"><a href="mersey_five.html#cb157-5" tabindex="-1"></a>  <span class="co"># Adds a 1:1 line for comparison</span></span>
<span id="cb157-6"><a href="mersey_five.html#cb157-6" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>) <span class="sc">+</span></span>
<span id="cb157-7"><a href="mersey_five.html#cb157-7" tabindex="-1"></a>  <span class="co"># Adds the point data, modifying the shape, size, colour and fill</span></span>
<span id="cb157-8"><a href="mersey_five.html#cb157-8" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">21</span>, <span class="at">colour =</span> <span class="st">&quot;white&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;#5695FF&quot;</span>, <span class="at">size =</span> <span class="fl">2.5</span>) <span class="sc">+</span></span>
<span id="cb157-9"><a href="mersey_five.html#cb157-9" tabindex="-1"></a>  <span class="co"># Setting the theme and aspect ratio</span></span>
<span id="cb157-10"><a href="mersey_five.html#cb157-10" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb157-11"><a href="mersey_five.html#cb157-11" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb157-12"><a href="mersey_five.html#cb157-12" tabindex="-1"></a>  <span class="co"># Axis limits</span></span>
<span id="cb157-13"><a href="mersey_five.html#cb157-13" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">60</span>)) <span class="sc">+</span></span>
<span id="cb157-14"><a href="mersey_five.html#cb157-14" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">60</span>)) <span class="sc">+</span></span>
<span id="cb157-15"><a href="mersey_five.html#cb157-15" tabindex="-1"></a>  <span class="co"># Add axis labels and a title</span></span>
<span id="cb157-16"><a href="mersey_five.html#cb157-16" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> Measured<span class="sc">~</span>Zn, <span class="at">y =</span> Modelled<span class="sc">~</span>Zn, </span>
<span id="cb157-17"><a href="mersey_five.html#cb157-17" tabindex="-1"></a>       <span class="at">title =</span> Plot<span class="sc">~</span>of<span class="sc">~</span>measured<span class="sc">~</span>vs.<span class="sc">~</span>modelled<span class="sc">~</span>Zn<span class="sc">~</span>values)</span>
<span id="cb157-18"><a href="mersey_five.html#cb157-18" tabindex="-1"></a></span>
<span id="cb157-19"><a href="mersey_five.html#cb157-19" tabindex="-1"></a>zn_plot</span></code></pre></div>
<p><img src="Practical_1_files/figure-html/unnamed-chunk-163-1.png" width="672" style="display: block; margin: auto;" /></p>
<blockquote>
<p>Does the regression line match the 1:1 line? Is there any evidence of under- or over-prediction? Are there any outliers? What <strong>types</strong> of errors can you identify?</p>
</blockquote>
<p>You could also assess this relationship statistically, using linear regression:</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="mersey_five.html#cb158-1" tabindex="-1"></a><span class="co"># Linear regression of measured vs. modelled Zn values</span></span>
<span id="cb158-2"><a href="mersey_five.html#cb158-2" tabindex="-1"></a>prediction_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> Zn <span class="sc">~</span> predicted_Zn, <span class="at">data =</span> testing)</span>
<span id="cb158-3"><a href="mersey_five.html#cb158-3" tabindex="-1"></a></span>
<span id="cb158-4"><a href="mersey_five.html#cb158-4" tabindex="-1"></a><span class="co"># Print summary statistics</span></span>
<span id="cb158-5"><a href="mersey_five.html#cb158-5" tabindex="-1"></a><span class="fu">summary</span>(prediction_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Zn ~ predicted_Zn, data = testing)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -19.0259  -1.8266   0.9415   1.9784  17.4476 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -11.7003     4.5105  -2.594   0.0183 *  
## predicted_Zn   1.5450     0.2259   6.838 2.12e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.657 on 18 degrees of freedom
## Multiple R-squared:  0.7221, Adjusted R-squared:  0.7066 
## F-statistic: 46.76 on 1 and 18 DF,  p-value: 2.121e-06</code></pre>
<blockquote>
<p>How well does our Zn model perform on the testing dataset, based on the above graphs/statistics? Is out-of-sample performance comparable to in-sample performance?</p>
</blockquote>
<p><br/></p>
<p><strong>To finish the practical</strong> and to prepare for the assessment:</p>
<blockquote>
<p>Replicating the above approaches, calculate regression equations based on stepwise linear regression for all 10 water quality indicators (NO<sub>2</sub>, pH, SSC, Ca, Mg, NH<sub>4</sub>, NO<sub>3</sub>, TON, PO<sub>4</sub>, Zn).</p>
</blockquote>
<blockquote>
<p>Save the relevant model coefficients and the R<sup>2</sup> and <em>p</em> values for each equation. These should be stored in a single table for the assessment.</p>
</blockquote>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body">
<div id="ref-amrhein_scientists_2019" class="csl-entry">
Amrhein, V. <em>et al.</em> (2019) <span>‘Scientists rise up against statistical significance’</span>, <em>Nature</em>, 567(7748), pp. 305–307. doi:<a href="https://doi.org/10.1038/d41586-019-00857-9">10.1038/d41586-019-00857-9</a>.
</div>
<div id="ref-andrade_p_2019" class="csl-entry">
Andrade, C. (2019) <span>‘The <span>P</span> <span>Value</span> and <span>Statistical</span> <span>Significance</span>: <span>Misunderstandings</span>, <span>Explanations</span>, <span>Challenges</span>, and <span>Alternatives</span>’</span>, <em>Indian Journal of Psychological Medicine</em>, 41(3), pp. 210–215. doi:<a href="https://doi.org/10.4103/IJPSYM.IJPSYM_193_19">10.4103/IJPSYM.IJPSYM_193_19</a>.
</div>
<div id="ref-goodman_dirty_2008" class="csl-entry">
Goodman, S. (2008) <span>‘A <span>Dirty</span> <span>Dozen</span>: <span>Twelve</span> <span>P</span>-<span>Value</span> <span>Misconceptions</span>’</span>, <em>Seminars in Hematology</em>, 45(3), pp. 135–140. doi:<a href="https://doi.org/10.1053/j.seminhematol.2008.04.003">10.1053/j.seminhematol.2008.04.003</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="mersey_four.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="Assessment.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
